from snakemake.utils import min_version

min_version("8.0")


include: "rules/common.smk"


wildcard_constraints:
    haplotype_sample="|".join(get_haplotype_samples()),
    sample_id="|".join(get_all_sample_ids()) if get_all_sample_ids() else ".+",


include: "rules/extract_sequences.smk"
include: "rules/align.smk"
include: "rules/graph.smk"
include: "rules/all_by_all.smk"


if ft_pileup_enabled():

    include: "rules/pileup.smk"


def get_all_outputs():
    outputs = [
        output_path("filtered_alignments/all.paf"),
        output_path("graphs/re_graph.graphml"),
        output_path("graphs/re_clusters.tsv"),
        output_path("graphs/consensus_peak_clusters.tsv"),
        output_path("all_by_all/re_pairwise_identity.tsv.gz"),
    ]
    if ft_pileup_enabled():
        outputs.extend(
            expand(
                output_path("pileup/{sample_id}.peaks.bed.gz"),
                sample_id=get_sample_ids_with_ft_bam(),
            )
        )
        outputs.append(output_path("pileup/peaks_with_clusters.bed.gz"))
    return outputs


rule all:
    input:
        get_all_outputs(),
